import java.util.Properties

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "bible-fob"
include(":app")

val localPropertiesFile = file("local.properties")
if (!localPropertiesFile.exists()) {
    val sdkCandidates = sequenceOf(
        System.getenv("ANDROID_HOME"),
        System.getenv("ANDROID_SDK_ROOT"),
        "${System.getProperty("user.home")}/Android/Sdk",
        "/opt/android-sdk",
        "/usr/local/android-sdk"
    )
        .filterNotNull()
        .map(::file)

    val discoveredSdk = sdkCandidates.firstOrNull { sdkDir ->
        sdkDir.exists() && sdkDir.resolve("platform-tools").exists()
    }

    if (discoveredSdk != null) {
        val properties = Properties().apply {
            setProperty("sdk.dir", discoveredSdk.absolutePath)
        }
        localPropertiesFile.outputStream().use { output ->
            properties.store(output, "Auto-generated by settings.gradle.kts")
        }
        println("[bible-fob] Auto-generated local.properties with sdk.dir=${discoveredSdk.absolutePath}")
    } else {
        println("[bible-fob] Android SDK not found. Set ANDROID_HOME/ANDROID_SDK_ROOT or create local.properties with sdk.dir.")
    }
}
